version: '3'
services:
  stats:
    image: python_ubuntu_t:v1.0
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ../workdir:/home/jovyan/workdir
    command: >
      jupyter lab --notebook-dir=/home/jovyan --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*'
